spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect
  properties:
    hibernate:
      format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  #      Mail properties
  mail:
    default-encoding: utf-8
    debug: true
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    host: smtp.gmail.com
    username: userportal0@gmail.com
    password: poran@258
    port: 587
server:
  port: 8080


#server.port=8080
#spring.mvc.throw-exception-if-no-handler-found=true
#
#  # Data source property
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/library_db
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#  #JPA properties. Using ddl-auto = create will drop schema every-time.
#  #Choose the correct property based on development / production role.
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.initialization-mode=always
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUg